# Generated by Django 3.1.6 on 2021-02-11 22:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-is_published', '-published_date', '-last_change_date'), 'verbose_name': 'Blogpost', 'verbose_name_plural': 'Blogposts'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(upload_to=blog.models.blog_image_directory_path, verbose_name='Thumbnail'),
        ),
    ]
